import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const genryuSans = localFont({
  variable: "--font-genryu",
  display: "swap",
  src: [
    { path: "../public/genryu/GenRyuMinTW-EL-01.woff2", weight: "200", style: "normal" },
    { path: "../public/genryu/GenRyuMinTW-L-01.woff2", weight: "300", style: "normal" },
    { path: "../public/genryu/GenRyuMinTW-R-01.woff2", weight: "400", style: "normal" },
    { path: "../public/genryu/GenRyuMinTW-M-01.woff2", weight: "500", style: "normal" },
    { path: "../public/genryu/GenRyuMinTW-SB-01.woff2", weight: "600", style: "normal" },
    { path: "../public/genryu/GenRyuMinTW-B-01.woff2", weight: "700", style: "normal" },
    { path: "../public/genryu/GenRyuMinTW-H-01.woff2", weight: "800", style: "normal" },
  ],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-TW" suppressHydrationWarning>
      <body
        className={`${genryuSans.variable} ${geistMono.variable} antialiased`}
      >
        <script
          dangerouslySetInnerHTML={{
            __html: `(${function setInitialTheme() {
              try {
                const persisted = window.localStorage.getItem('theme')
                if (typeof persisted === 'string') {
                  if (persisted === 'dark') {
                    document.documentElement.classList.add('dark')
                    document.documentElement.style.colorScheme = 'dark'
                  } else {
                    document.documentElement.classList.remove('dark')
                    document.documentElement.style.colorScheme = 'light'
                  }
                  return
                }
                const mql = window.matchMedia('(prefers-color-scheme: dark)')
                if (mql.matches) {
                  document.documentElement.classList.add('dark')
                  document.documentElement.style.colorScheme = 'dark'
                } else {
                  document.documentElement.classList.remove('dark')
                  document.documentElement.style.colorScheme = 'light'
                }
              } catch (e) { }
            }.toString()})();`,
          }}
        />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
